# Generated by Django 5.0.2 on 2024-03-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('0', 'J.D.O.O.'), ('1', 'D.O.O.'), ('3', 'D.D.'), ('4', 'OBRT'), ('5', 'NEPROFITNA ORGANIZACIJA')], max_length=1)),
                ('size', models.CharField(blank=True, choices=[('0', 'MIKRO'), ('1', 'MALI'), ('3', 'SREDNJI'), ('4', 'VELIKI')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('post_number', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('mob', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('director_address', models.CharField(blank=True, max_length=200)),
                ('director_oib', models.CharField(blank=True, max_length=200)),
                ('oib', models.CharField(max_length=11)),
                ('vat_id', models.CharField(blank=True, max_length=13)),
                ('reg_number', models.CharField(blank=True, max_length=20)),
                ('stat_number', models.CharField(blank=True, max_length=20)),
                ('hzmo_number', models.CharField(blank=True, max_length=20)),
                ('hzzo_number', models.CharField(blank=True, max_length=20)),
                ('pdv', models.CharField(choices=[('0', 'NIJE OBVEZNIK'), ('1', 'MJESEČNI'), ('3', 'KVARTALNI')], max_length=1)),
                ('number_worker', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_plan_app.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('recurring', models.CharField(blank=True, choices=[('0', 'DA'), ('1', 'NE')], max_length=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_plan_app.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
