# Generated by Django 5.0.2 on 2024-03-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring_period',
            field=models.CharField(blank=True, choices=[('0', 'GODIŠNJE'), ('1', 'MJESEČNO'), ('2', 'TJEDNO'), ('3', 'DNEVNO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.CharField(blank=True, choices=[('0', 'NE'), ('1', 'DA')], max_length=1),
        ),
    ]
